export const FETCHING = 'Fetching';
export const SET_COORDINATES = 'Set coordinates';
export const SET_ERROR = 'Set error';
export const CLEAR_ERROR = 'Clear error';
export const SET_CITY = 'Set city';
export const SET_FORECAST = 'Set weather forecast';
export const SET_FAHRENHEIT_UNIT = 'Set Fahrenheit unit';
export const SET_CELCIUS_UNIT = 'Set Celcius unit';
export const SET_CURRENT_LOCATION = 'Set current locaiton';
